### ISSUE TITLE
[aula 4] Dúvida sobre PAAS & SAAS

### ISSUE THREAD

**Issue by ghost** [iagoac/dce540#10]
Serviços específicos como os planos básicos da hostgator e godaddy permitindo acesso restrito a um ambiente PHP se encaixam como PAAS ou SAAS? SAAS seria o software pronto servido a uma taxa fixa? ambientes como o amazon EC2 são IAAS ou PAAS?

**Comment by iagoac** [comment]
@PhiCross5 estes serviços tipo hostgator, godaddy ou outros ambientes de hospedagem online normalmente são classificados como PaaS. Esta classificação incorre do fato de que eles provêm, além do software, toda a parte de hardware necessária para a hospedagem do seu site ou sistema.

Já ambientes em cloud como o EC2 da Amazon e o Azure da Microsoft são definidos como IaaS. Eles se diferem de ambientes de hospedagem mais simples por dar mais liberdade ao usuário de configurar quais recursos de hardware ele precisa (quantos Gb de RAM, processador, armazenamento, etc). Dado esta liberdade, eles são definidos como infraestrutura.

Dê uma olhada em https://www.darede.com.br/saas-paas-e-iaas-o-que-significa/?gclid=Cj0KCQiAhf2MBhDNARIsAKXU5GThl9nwZAzh1F-tn9lQuVCgRBC8CKf8JlBIjwuUb8bm8QCcZlWDYnUaAjhgEALw_wcB

**Comment by iagoac** [comment]
Esqueci de falar sobre o SaaS! Este último se refere somente a software, não sendo disponibilizado nenhum recurso de hardware aos usuários. Muitas vezes você tem SaaS com APIs REST e RESTFUL web, onde você faz uma chamada a um serviço online (como processamento de imagem, reconhecimento de padrões ou algo parecido) e você obtém o resultado necessário.

Um ótimo exemplo de SaaS seria o IBM Watson (https://www.ibm.com/watson/products-services)
