### ISSUE TITLE
Aulas 07 e 08

### ISSUE THREAD

**Issue by caiomarinello** [iagoac/dce540#11]
Quando serão postadas as aulas 07 e 08?

**Comment by LuScarton** [comment]
F

**Comment by iagoac** [comment]
Estou resolvendo o planejamento do restante do semestre. Hoje serão postadas as aulas 07 e 08 e amanhã a 09 e 10.  
Vou tentar postar o semestre inteiro até o Natal
Peço desculpas a vocês pelo atraso nestas aulas
