### ISSUE TITLE
Prova 21/12

### ISSUE THREAD

**Issue by JoaoBianco** [iagoac/dce540#12]
Bom dia professor, vi que disponibilizou todas as aulas antes da prova e gostaria de saber qual o horário que a prova vai ser aplicada, se será apenas no horário da aula (14h às 16h) ou terá um tempo maior?

Obrigado.

**Comment by iagoac** [comment]
Olá @JoaoBianco eu vou discutir esse tema com vocês hoje, conforme e-mail que enviei alguns minutos atrás.  

Entretanto, a prova terá uma duração maior. Ela terá início no horário da aula e prazo de entrega de 24 horas
