### ISSUE TITLE
Adiamento prova 21/12

### ISSUE THREAD

**Issue by JoaoBianco** [iagoac/dce540#13]
Como solicitado por e-mail, venho solicitar o adiamento da prova para janeiro.

**Comment by Lucas1470** [comment]
Concordo!

**Comment by iagoac** [comment]
A data que temos disponível é dia 25 de Janeiro (uma terça-feira).  
O recesso acaba no dia 24 e temos que dar prosseguimento a disciplina a partir do dia 27.

Caso vocês concordem com esta data, não teremos mais aulas de agora até o dia da prova

**Comment by DenisCoutinho** [comment]
Também gostaria que fosse adiada, esse finalzinho de ano tá bem apertado pra geral e acredito que se for adiada para Janeiro a galera vai ter mais folga pra estudar

**Comment by caiomarinello** [comment]
Concordo com o adiamento também.

**Comment by morais15** [comment]
Concordo.

**Comment by gabriel-takahiro** [comment]
Concordo.

**Comment by dudusapio** [comment]
Concordo com o adiamento e te peço que poste as aulas nos dias previstos delas, porque isso acaba nos atrasando e acumulando matéria e nem é culpa nossa.

**Comment by brunafalcucci** [comment]
Concordo super com o adiamento

**Comment by willsoares** [comment]
De acordo

**Comment by PedroBortolin** [comment]
Concordo com o adiamento!

**Comment by vitor-rubatino** [comment]
Também concordo com o adiamento!

**Comment by Cadu-Pavao** [comment]
Concordo 100% com o adiamento! Estamos tendo uma gama boa de atividades + provas, passar esta prova para janeiro ajudaria bastante.

**Comment by LuScarton** [comment]
Concordo com o adiamento e também com o Eduardo Sapio! Se você pudesse postar as aulas nos dias previstos, seria muito bom! Porque essa falta de organização (exemplo: postando a aula 3 antes da aula 2, depois posta 3 aulas tudo no mesmo dia pq tava tudo atrasado etc) acaba atrapalhando em outras disciplinas e fica difícil até pra gente se organizar também, pois nunca sabemos ao certo quando as aulas serão postadas! E se você também pudesse avisar no Moodle quando postasse as novas aulas, também ajudaria muito em nossa organização!

**Comment by daniele4silva** [comment]
Concordo com o adiamento

**Comment by R50UZ4** [comment]
Concordo
