### ISSUE TITLE
acesso de computadores separados em LAN

### ISSUE THREAD

**Issue by ghost** [iagoac/dce540#16]
quero testar RPC e outros esquemas de IPC via rede em dois hosts separados mas não consigo fazer com que os mesmos se comuniquem via rede LAN (IP prefixo 192.168). É necessário algum procedimento na rede para habilitar acesso entre eles?

**Comment by willsoares** [comment]
Pode ser que você tenha que abrir portas no firewall e no roteador.
Mas provavelmente deve funcionar sem problemas em uma rede local

**Comment by iagoac** [comment]
@PhiCross5 não faz muito sentido que isto não funcione em sua rede local. Como o @willsoares disse, verifique se o seu firewall está corretamente configurado e se o roteador permite este tipo de comunicação.

Uma outra forma interessante de você fazer isto é utilizando um único computador e máquinas virtuais. Dê um exemplo [neste pequeno tutorial](https://kubemq.io/rpc-message-in-kubernetes-or-docker/) utilizando docker

**Comment by ghost** [comment]
Alterei algumas configurações no roteador da minha rede e funcionou.
O roteador deve ter bloqueado conexão entre IPs dinâmicos, mas é algo
específico à minha rede

Em sex., 28 de jan. de 2022 às 15:25, Iago Augusto de Carvalho <
***@***.***> escreveu:
