### ISSUE TITLE
Qual  conteúdo que vai cair na nossa segunda prova ?

### ISSUE THREAD

**Issue by dudusapio** [iagoac/dce540#17]

**Comment by iagoac** [comment]
Somente as aulas 15 a 17.  
A matéria desta prova é mais curta

**Comment by dudusapio** [comment]
Beleza! A prova vai ser no horário da aula ?

**Comment by iagoac** [comment]
@dudusapio sim!
Eu avisei no e-mail para a turma: a prova vai ter início no horário da aula e deverá ser entregue até o fim de sexta-feira
