### ISSUE TITLE
Correção da prova

### ISSUE THREAD

**Issue by leonardo-pessoa** [iagoac/dce540#19]
Boa tarde, Iago!
Você irá disponibilizar as provas corrigidas?
Gostaria de saber o que errei.

**Comment by iagoac** [comment]
@leonardo-pessoa eu não tenho as correções das provas digitalizadas.  

Entretanto, na planilha com as notas disponibilizada [aqui](https://github.com/iagoac/dce540/blob/main/notas.xlsx), você consegue encontrar sua nota em cada uma das questões separadas. Basta você abrir a planilha em seu computador e olhar a fórmula utilizada para o cômputo de sua nota.

Caso você tenha dúvidas, podemos marcar um horário para conversarmos rapidamente

**Comment by leonardo-pessoa** [comment]
Ok, no exercício 6 da prova 1, qual era o valor de cada item? a, b e c?

**Comment by iagoac** [comment]
Considerei um acerto como 7 pontos. Dois acertos seriam 14 pontos e a pontuação máxima, 20 (como descrito na questão)

**Comment by leonardo-pessoa** [comment]
Depois você pode dar uma olhada na minha prova? Acredito ter obtido dois acertos no exercício 6.

**Comment by iagoac** [comment]
Você tem razão.  
Atualizei sua nota na planilha e vou atualizar neste exato momento no sistema acadêmico.

Com isto, vou também fechar este issue.

**Comment by leonardo-pessoa** [comment]
Beleza, muito obrigado. :)
