### ISSUE TITLE
Cronograma das aulas práticas.

### ISSUE THREAD

**Issue by night-jpg** [iagoac/dce540#2]
Há datas estabelecidas para os trabalhos práticos? Serão Síncronos?

**Comment by iagoac** [comment]
Olá Pedro,

ainda estamos em um ponto da disciplina que não existe nenhum conteúdo para o qual possam ser realizados trabalhos práticos.
Eu estou planejando as atividades e informarei em data oportuna.

Entretanto, todos os trabalhos práticos serão realizados de forma assíncrona, tendo um tempo mínimo de entrega de 7 dias
