### ISSUE TITLE
Duvida na aula 4

### ISSUE THREAD

**Issue by vitorhugoclz** [iagoac/dce540#5]
Acredito que houve uma confusão na hora de falar sobre os 4 métodos HTTP utilizados em aplicações REST

Normalmente o POST é utilizado para criar um novo dado/recurso, enquanto o PUT é utilizado para atualizar a informação de um dado/recurso. 

Fonte: [https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Methods](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Methods)

**Comment by iagoac** [comment]
@vitorhugoclz estou revisando estas informações. Atualizo este _issue_ amanhã com a resposta
