### ISSUE TITLE
Duvida da prova. Questão 6

### ISSUE THREAD

**Issue by arimstefanini** [iagoac/dce540#6]
Eu não entendi o que precisa ser feito. Já procurei em todo lugar e não me lembro de formulas matemáticas. Poderia dizer o que exactamente você deseja na questão 6

**Comment by iagoac** [comment]
@arimstefanini eu quero o calculo do speed-up, isto é, a diferença entre o tempo de execução serial e o tempo de execução paralela de um algoritmo.  

Quando temos decoposição de domínio, é simples utilizar a Lei de Amdahl. Já quando temos decomposição funcional, não existe uma fórmula ou regra fechada e deve-se levar em consideração o tempo de sincronização de todas as sub-tarefas
