### ISSUE TITLE
Prática 01

### ISSUE THREAD

**Issue by arimstefanini** [iagoac/dce540#7]
Iago,
Para realizar a implementação da Prática 01 é necessário criar a conexão com um servidor, localhost?

**Comment by iagoac** [comment]
@arimstefanini não é necessário. Você pode definir duas classes (classe no sentido de programação orientada a objetos mesmo), sendo uma que faz o papel do servidor e outra que faz o papel do cliente.

**Comment by vitorhugoclz** [comment]
Professor fiz um código utilizando a biblioteca xmlrpc do python que faz uma comunicação via socket.
Nessa implementação é necessário rodar dois arquivos distintos um servidor e um cliente. Essa implementação também pode ser entregada no trabalho ou necessariamente precisa ser essa implementação de orientação objetos feita em um Jupyter notebook?

**Comment by iagoac** [comment]
@vitorhugoclz minha ideia realmente é que vocês façam a entrega de um único Jupyter.  
As próximas implementações vão necessitar da implementação de sockets e/ou MPI.

**Comment by GustavoHenriqueSant** [comment]
Iago, a main deve implementar padronização das informações ou algo do tipo como um middleware ?Pq se não seria só a implementação de classes, e instancia-las na main. É isso mesmo o esperado na atividade ?

**Comment by iagoac** [comment]
@GustavoHenriqueSant realmente é bem mais simples do que parece.   
Um middleware nada mais é do que uma classe que implementa os métodos e algoritmos para gerenciamento de um sistema distribuído. Neste caso, ele não possui um nome específico, pois vocês estão utilizando a _main_ como se fosse o middleware
