### ISSUE TITLE
Dúvida da Prova. Exercício 2.

### ISSUE THREAD

**Issue by night-jpg** [iagoac/dce540#8]
Existe algum tempo de programa específico para se imprimir o desvio de clock dos dispositivos do sistema distribuído de um computador? Estou com dúvida.

**Comment by iagoac** [comment]
@night-jpg não existe um tempo específico. Aliás, isto não faz nenhuma diferença na resolução do exercício  
O interessante é notar que todos os desvios de clock são observados em um mesmo tempo _t_ para todos os dispositivos
